# Generated by Django 6.0.6 on 2026-06-08 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', '文字'), ('image', '图片')], default='text', max_length=10, verbose_name='块类型')),
                ('content', models.TextField(blank=True, verbose_name='文字内容')),
                ('layout', models.CharField(choices=[('top-bottom', '上图下文'), ('bottom-top', '上文下图'), ('left-right', '左图右文'), ('right-left', '左文右图'), ('float-left', '文字环绕'), ('full', '仅内容')], default='full', max_length=20, verbose_name='图文布局')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.postimage', verbose_name='引用图片')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='blog.post', verbose_name='所属文章')),
            ],
            options={
                'verbose_name': '内容块',
                'verbose_name_plural': '内容块',
                'ordering': ['order'],
            },
        ),
    ]
