# Generated by Django 6.0.6 on 2026-06-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contentblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_layout',
            field=models.CharField(choices=[('top', '封面上，标题下'), ('left', '封面左，标题右'), ('right', '标题左，封面右'), ('bg', '封面全宽背景')], default='top', max_length=20, verbose_name='封面布局'),
        ),
    ]
