# Generated by Django 5.2.15 on 2026-06-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_add_subtitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['order', '-created_at'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AddField(
            model_name='post',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
    ]
